package com.blanke.mdwechat

import com.blanke.mdwechat.bean.ViewTreeItem

object ViewTreeRepo {
    val ConversationListViewItem: ViewTreeItem by lazy {
        ViewTreeItem(
                CC.LinearLayout.name,
                arrayOf(
                        ViewTreeItem(
                                CC.RelativeLayout.name,
                                arrayOf(
                                        ViewTreeItem(CC.ImageView.name),
                                        ViewTreeItem(CC.TextView.name),
                                        ViewTreeItem(CC.ImageView.name)
                                )
                        ),
                        ViewTreeItem(
                                CC.LinearLayout.name,
                                arrayOf(
                                        ViewTreeItem(
                                                CC.LinearLayout.name,
                                                arrayOf(
                                                        ViewTreeItem(
                                                                CC.LinearLayout.name,
                                                                arrayOf(
                                                                        ViewTreeItem(Classes.NoMeasuredTextView.name)
                                                                )
                                                        ),
                                                        ViewTreeItem(Classes.NoMeasuredTextView.name)
                                                )
                                        ),
                                        ViewTreeItem(
                                                CC.LinearLayout.name,
                                                arrayOf(
                                                        ViewTreeItem(
                                                                CC.LinearLayout.name,
                                                                arrayOf(
                                                                        ViewTreeItem(CC.ImageView.name),
                                                                        ViewTreeItem(Classes.NoMeasuredTextView.name)
                                                                )
                                                        ),
                                                        ViewTreeItem(
                                                                CC.LinearLayout.name,
                                                                arrayOf(
                                                                        ViewTreeItem(CC.ImageView.name),
                                                                        ViewTreeItem(CC.ImageView.name),
                                                                        ViewTreeItem(CC.ImageView.name),
                                                                        ViewTreeItem(CC.ImageView.name)
                                                                )
                                                        )

                                                )
                                        )
                                )
                        )
                )
        )
    }

    val ContactListViewItem: ViewTreeItem by lazy {
        ViewTreeItem(
                Classes.NoDrawingCacheLinearLayout.name,
                arrayOf(
                        ViewTreeItem(CC.TextView.name),
                        ViewTreeItem(
                                CC.LinearLayout.name,
                                arrayOf(
                                        ViewTreeItem(
                                                CC.RelativeLayout.name,
                                                arrayOf(
                                                        ViewTreeItem(CC.TextView.name),
                                                        ViewTreeItem(CC.TextView.name),
                                                        ViewTreeItem(CC.TextView.name),
                                                        ViewTreeItem("com.tencent.mm.ui.AddressView")
                                                )
                                        )
                                )
                        )
                )
        )
    }

    val DiscoverViewItem: ViewTreeItem by lazy {
        ViewTreeItem(
                CC.LinearLayout.name,
                arrayOf(
                        ViewTreeItem(
                                CC.LinearLayout.name,
                                arrayOf(
                                        ViewTreeItem(
                                                CC.LinearLayout.name,
                                                arrayOf(
                                                        ViewTreeItem(
                                                                CC.LinearLayout.name,
                                                                arrayOf(
                                                                        ViewTreeItem("com.tencent.mm.ui.MMImageView"),
                                                                        ViewTreeItem(
                                                                                CC.LinearLayout.name,
                                                                                arrayOf(
                                                                                        ViewTreeItem(
                                                                                                CC.LinearLayout.name,
                                                                                                arrayOf(
                                                                                                        ViewTreeItem(CC.TextView.name),
                                                                                                        ViewTreeItem(CC.TextView.name),
                                                                                                        ViewTreeItem(CC.ImageView.name)
                                                                                                )
                                                                                        ),
                                                                                        ViewTreeItem(CC.TextView.name)
                                                                                )
                                                                        )
                                                                )
                                                        )
                                                )
                                        )
                                )
                        )
                )
        )
    }

    val SettingAvatarView: ViewTreeItem by lazy {
        ViewTreeItem(
                CC.LinearLayout.name,
                arrayOf(
                        ViewTreeItem(
                                CC.RelativeLayout.name,
                                arrayOf(
                                        ViewTreeItem(CC.ImageView.name),
                                        ViewTreeItem(
                                                CC.LinearLayout.name,
                                                arrayOf(
                                                        ViewTreeItem(Classes.NoMeasuredTextView.name),
                                                        ViewTreeItem(CC.TextView.name)
                                                )
                                        ),
                                        ViewTreeItem(CC.TextView.name)
                                )
                        ),
                        ViewTreeItem(CC.ImageView.name)
                )
        )
    }
}